version: "3.8"

services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - "8889:8888"  # Usando porta 8889 para evitar conflito com seu container existente
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
      - ./src:/home/jovyan/work/src
      - ./models:/home/jovyan/work/models
      - ./results:/home/jovyan/work/results
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=706f99d65538d22f711734ae224e738c5560e191476a74354f32a1de523dd91e

     networks:
      - jupyter_network

  networks:
   jupyter_network:
    driver: bridge
